apiVersion: v1
kind: ConfigMap
metadata:
  name: nexora-config
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nexora-secret
type: Opaque
stringData:
{{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
